# PyTorch Basics - Tensors and Operations

## Objectives
- Understand PyTorch tensors and how they differ from NumPy arrays
- Learn tensor creation, indexing, and reshaping
- Master GPU vs CPU computation
- Perform mathematical operations on tensors

## What is a PyTorch Tensor?
A tensor is the fundamental data structure in PyTorch - essentially a multi-dimensional array that can be computed on GPUs.

## What We're About to Do

The code below imports essential libraries. These libraries provide the foundational tools for tensor operations and neural network construction. Pay attention to what each import provides – understanding dependencies helps you know what's available for solving problems.


In [3]:
# Import necessary libraries for tensor operations and deep learning
import torch
import numpy as np
import matplotlib.pyplot as plt

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")


PyTorch version: 2.1.2+cpu
CUDA available: False


## 1. Tensor Creation

In [4]:
# Execute code with detailed step-by-step process
# Create tensor from Python list
x = torch.tensor([1, 2, 3])
print(f"From list: {x}")
print(f"Shape: {x.shape}")
print(f"Data type: {x.dtype}")

# Create 2D tensor
matrix = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(f"\nMatrix:\n{matrix}")
print(f"Matrix shape: {matrix.shape}")


From list: tensor([1, 2, 3])
Shape: torch.Size([3])
Data type: torch.int64

Matrix:
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Matrix shape: torch.Size([3, 2])


In [5]:
# Execute code with detailed step-by-step process
# Common tensor creation methods
zeros = torch.zeros(3, 4)  # Matrix of zeros
ones = torch.ones(2, 3)    # Matrix of ones
random = torch.randn(2, 3) # Random normal distribution
uniform = torch.rand(2, 3) # Uniform [0, 1)

print(f"Zeros:\n{zeros}\n")
print(f"Ones:\n{ones}\n")
print(f"Random (normal):\n{random}\n")
print(f"Random (uniform):\n{uniform}")


Zeros:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random (normal):
tensor([[-0.4754,  0.0014, -0.5820],
        [ 0.6318,  1.1577,  1.3065]])

Random (uniform):
tensor([[0.0437, 0.3096, 0.2627],
        [0.0910, 0.8595, 0.9171]])


In [6]:
# Execute code with detailed step-by-step process
# Create tensor with specific range
arange = torch.arange(0, 10, 2)  # 0 to 10, step 2
linspace = torch.linspace(0, 1, 5)  # 5 points from 0 to 1
identity = torch.eye(3)  # Identity matrix

print(f"Arange: {arange}")
print(f"Linspace: {linspace}")
print(f"Identity:\n{identity}")


Arange: tensor([0, 2, 4, 6, 8])
Linspace: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
Identity:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## 2. Tensor Properties

In [7]:
# Execute code with detailed step-by-step process
x = torch.randn(2, 3, 4)

print(f"Shape: {x.shape}")
print(f"Size: {x.size()}")
print(f"Dimensions (ndim): {x.ndim}")
print(f"Number of elements: {x.numel()}")
print(f"Data type: {x.dtype}")
print(f"Device: {x.device}")


Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Dimensions (ndim): 3
Number of elements: 24
Data type: torch.float32
Device: cpu


In [8]:
# Execute code with detailed step-by-step process
# Different data types
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
double_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)
bool_tensor = torch.tensor([True, False, True])

print(f"Int32: {int_tensor.dtype}")
print(f"Float32: {float_tensor.dtype}")
print(f"Float64: {double_tensor.dtype}")
print(f"Bool: {bool_tensor.dtype}")


Int32: torch.int32
Float32: torch.float32
Float64: torch.float64
Bool: torch.bool


## 3. Indexing and Slicing

In [9]:
# Execute code with detailed step-by-step process
x = torch.arange(12).reshape(3, 4)
print(f"Tensor:\n{x}\n")

# Basic indexing
print(f"First row: {x[0]}")
print(f"Element [1,2]: {x[1, 2]}")
print(f"Last row: {x[-1]}")


Tensor:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

First row: tensor([0, 1, 2, 3])
Element [1,2]: 6
Last row: tensor([ 8,  9, 10, 11])


In [10]:
# Execute code with detailed step-by-step process
# Slicing
print(f"First two rows:\n{x[:2]}")
print(f"\nAll rows, first 2 columns:\n{x[:, :2]}")
print(f"\nEvery other element (rows):\n{x[::2]}")
print(f"\nEvery other element (cols):\n{x[:, ::2]}")


First two rows:
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

All rows, first 2 columns:
tensor([[0, 1],
        [4, 5],
        [8, 9]])

Every other element (rows):
tensor([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]])

Every other element (cols):
tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10]])


## 4. Reshaping and Transposing

In [11]:
# Execute code with detailed step-by-step process
x = torch.arange(12)
print(f"Original: {x.shape} - {x}\n")

# Reshape
reshaped = x.reshape(3, 4)
print(f"Reshaped (3, 4):\n{reshaped}\n")

reshaped2 = x.reshape(2, 2, 3)
print(f"Reshaped (2, 2, 3):\n{reshaped2}\n")

# Flatten
flattened = reshaped.flatten()
print(f"Flattened: {flattened}")


Original: torch.Size([12]) - tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Reshaped (3, 4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Reshaped (2, 2, 3):
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

Flattened: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [12]:
# Execute code with detailed step-by-step process
x = torch.arange(6).reshape(2, 3)
print(f"Original shape: {x.shape}")
print(f"Original:\n{x}\n")

# Transpose
transposed = x.T
print(f"Transposed shape: {transposed.shape}")
print(f"Transposed:\n{transposed}")


Original shape: torch.Size([2, 3])
Original:
tensor([[0, 1, 2],
        [3, 4, 5]])

Transposed shape: torch.Size([3, 2])
Transposed:
tensor([[0, 3],
        [1, 4],
        [2, 5]])


## 5. Mathematical Operations

In [13]:
# Execute code with detailed step-by-step process
a = torch.tensor([1, 2, 3], dtype=torch.float32)
b = torch.tensor([4, 5, 6], dtype=torch.float32)

print(f"a: {a}")
print(f"b: {b}")
print(f"\nElement-wise add: {a + b}")
print(f"Element-wise sub: {a - b}")
print(f"Element-wise mul: {a * b}")
print(f"Element-wise div: {a / b}")
print(f"Power: {a ** 2}")


a: tensor([1., 2., 3.])
b: tensor([4., 5., 6.])

Element-wise add: tensor([5., 7., 9.])
Element-wise sub: tensor([-3., -3., -3.])
Element-wise mul: tensor([ 4., 10., 18.])
Element-wise div: tensor([0.2500, 0.4000, 0.5000])
Power: tensor([1., 4., 9.])


In [14]:
# Execute code with detailed step-by-step process
# Statistical operations
x = torch.randn(2, 3, 4)
print(f"Mean: {x.mean()}")
print(f"Std: {x.std()}")
print(f"Sum: {x.sum()}")
print(f"Min: {x.min()}")
print(f"Max: {x.max()}")
print(f"Mean along axis 1 shape: {x.mean(dim=1).shape}")


Mean: 0.15197868645191193
Std: 0.9647318720817566
Sum: 3.647488594055176
Min: -1.0832144021987915
Max: 2.22468900680542
Mean along axis 1 shape: torch.Size([2, 4])


In [15]:
# Execute code with detailed step-by-step process
# Matrix multiplication
a = torch.randn(3, 4)
b = torch.randn(4, 2)

result = torch.matmul(a, b)
print(f"a shape: {a.shape}")
print(f"b shape: {b.shape}")
print(f"Result shape: {result.shape}")

# Using @ operator
result2 = a @ b
print(f"Same using @: {torch.allclose(result, result2)}")


a shape: torch.Size([3, 4])
b shape: torch.Size([4, 2])
Result shape: torch.Size([3, 2])
Same using @: True


## 6. Broadcasting

In [16]:
# Execute code with detailed step-by-step process
# Broadcasting example
x = torch.randn(3, 1)
y = torch.randn(1, 4)

print(f"x shape: {x.shape}")
print(f"y shape: {y.shape}")
print(f"x + y shape: {(x + y).shape}")

# Explicit example
a = torch.tensor([[1], [2], [3]])  # shape (3, 1)
b = torch.tensor([10, 20, 30, 40])  # shape (4,)

result = a + b  # Broadcast to (3, 4)
print(f"\nBroadcasting example:\n{result}")


x shape: torch.Size([3, 1])
y shape: torch.Size([1, 4])
x + y shape: torch.Size([3, 4])

Broadcasting example:
tensor([[11, 21, 31, 41],
        [12, 22, 32, 42],
        [13, 23, 33, 43]])


## 7. GPU vs CPU

In [17]:
# Execute code with detailed step-by-step process
# Check CUDA availability
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"GPU count: {torch.cuda.device_count()}")
if torch.cuda.is_available():
    print(f"Current GPU: {torch.cuda.get_device_name(0)}")


CUDA available: False
GPU count: 0


In [18]:
# Create on CPU
x_cpu = torch.randn(3, 4)
print(f"x_cpu device: {x_cpu.device}")

# Move to GPU (if available)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
x_gpu = x_cpu.to(device)
print(f"x_gpu device: {x_gpu.device}")

# Alternative syntax
x_gpu2 = x_cpu.cuda() if torch.cuda.is_available() else x_cpu
print(f"x_gpu2 device: {x_gpu2.device}")

x_cpu device: cpu
x_gpu device: cpu
x_gpu2 device: cpu


In [19]:
# Best practice: use device variable
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Create directly on device
x = torch.randn(3, 4, device=device)
y = torch.randn(3, 4, device=device)

# Operations on same device
z = x + y
print(f"Result device: {z.device}")

Result device: cpu


## 8. NumPy Interoperability

In [20]:
# Execute code with detailed step-by-step process
# NumPy to PyTorch
np_array = np.array([[1, 2, 3], [4, 5, 6]])
torch_tensor = torch.from_numpy(np_array)

print(f"NumPy type: {type(np_array)}")
print(f"PyTorch type: {type(torch_tensor)}")
print(f"PyTorch dtype: {torch_tensor.dtype}")

# PyTorch to NumPy
torch_tensor2 = torch.randn(2, 3)
np_array2 = torch_tensor2.numpy()

print(f"\nNumPy shape: {np_array2.shape}")
print(f"NumPy dtype: {np_array2.dtype}")


NumPy type: <class 'numpy.ndarray'>
PyTorch type: <class 'torch.Tensor'>
PyTorch dtype: torch.int32

NumPy shape: (2, 3)
NumPy dtype: float32


## 9. In-place Operations

In [21]:
# Execute code with detailed step-by-step process
x = torch.tensor([1.0, 2.0, 3.0])
print(f"Original x: {x}")
print(f"Original x id: {id(x)}")

# Out-of-place operation
y = x + 1
print(f"\nAfter y = x + 1:")
print(f"x: {x}")
print(f"y: {y}")
print(f"y id: {id(y)}")

# In-place operation (note the underscore)
x.add_(1)
print(f"\nAfter x.add_(1):")
print(f"x: {x}")
print(f"x id: {id(x)}")


Original x: tensor([1., 2., 3.])
Original x id: 2464772711696

After y = x + 1:
x: tensor([1., 2., 3.])
y: tensor([2., 3., 4.])
y id: 2464772718032

After x.add_(1):
x: tensor([2., 3., 4.])
x id: 2464772711696


## 10. Practice Exercise

**Task**: Create a batch of 32 random images (3 channels, 224x224 pixels each), move to GPU, compute mean and std

In [22]:
# Execute code with detailed step-by-step process
# Solution
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Create batch of images
batch_size = 32
channels = 3
height, width = 224, 224

images = torch.randn(batch_size, channels, height, width, device=device)

print(f"Batch shape: {images.shape}")
print(f"Device: {images.device}")
print(f"Mean: {images.mean():.4f}")
print(f"Std: {images.std():.4f}")


Batch shape: torch.Size([32, 3, 224, 224])
Device: cpu
Mean: 0.0003
Std: 1.0000
